from pyspark.sql import DataFrame
from pyspark.sql import functions as F


def build_fact_arrival_observation(
    silver_df: DataFrame,
    dim_station_df: DataFrame,
    dim_line_df: DataFrame,
    dim_date_df: DataFrame,
) -> DataFrame:

    source_df = (
        silver_df
        .withColumn(
            "prediction_local_date",
            F.to_date(
                F.from_utc_timestamp(
                    F.col("prediction_timestamp"),
                    "Europe/London",
                )
            ),
        )
    )

    with_station_df = (
        source_df.alias("fact")
        .join(
            dim_station_df.alias("station"),
            (
                F.col(
                    "fact.requested_stop_point_id"
                )
                ==
                F.col(
                    "station.station_id"
                )
            )
            &
            (
                F.col(
                    "fact.prediction_timestamp"
                )
                >=
                F.col(
                    "station.effective_from"
                )
            )
            &
            (
                F.col(
                    "station.effective_to"
                ).isNull()
                |
                (
                    F.col(
                        "fact.prediction_timestamp"
                    )
                    <
                    F.col(
                        "station.effective_to"
                    )
                )
            ),
            how="inner",
        )
    )

    with_line_df = (
        with_station_df
        .join(
            dim_line_df.alias("line"),
            (
                F.col("fact.line_id")
                ==
                F.col("line.line_id")
            )
            &
            (
                F.col(
                    "fact.prediction_timestamp"
                )
                >=
                F.col(
                    "line.effective_from"
                )
            )
            &
            (
                F.col(
                    "line.effective_to"
                ).isNull()
                |
                (
                    F.col(
                        "fact.prediction_timestamp"
                    )
                    <
                    F.col(
                        "line.effective_to"
                    )
                )
            ),
            how="inner",
        )
    )

    return (
        with_line_df
        .join(
            dim_date_df.alias("date"),
            F.col(
                "fact.prediction_local_date"
            )
            ==
            F.col(
                "date.calendar_date"
            ),
            how="inner",
        )
        .select(
            F.col(
                "fact.arrival_observation_key"
            ),
            F.col(
                "station.station_key"
            ),
            F.col(
                "line.line_key"
            ),
            F.col(
                "fact.requested_stop_point_id"
            ).alias(
                "requested_station_id"
            ),
            F.col(
                "fact.line_id"
            ),
            F.col(
                "date.date_key"
            ).alias(
                "prediction_date_key"
            ),
            F.col(
                "fact.request_id"
            ),
            F.col(
                "fact.arrival_id"
            ),
            F.col(
                "fact.vehicle_id"
            ),
            F.col(
                "fact.naptan_id"
            ),
            F.col(
                "fact.station_name"
            ),
            F.col(
                "fact.line_name"
            ),
            F.col(
                "fact.platform_name"
            ),
            F.col(
                "fact.direction"
            ),
            F.col(
                "fact.destination_naptan_id"
            ),
            F.col(
                "fact.destination_name"
            ),
            F.col(
                "fact.prediction_timestamp"
            ),
            F.col(
                "fact.expected_arrival"
            ),
            F.col(
                "fact.time_to_station_seconds"
            ),
            F.col(
                "fact.current_location"
            ),
            F.col(
                "fact.towards"
            ),
            F.col(
                "fact.mode_name"
            ),
            F.col(
                "fact.snapshot_at"
            ),
            F.col(
                "fact.source"
            ),
        )
    )